#!/bin/bash
# shieldnode — lib/nft.sh: генератор таблицы inet shieldnode (ТЗ §21–26, §30).
# Только ГЕНЕРАЦИЯ текста ruleset. Применение — в firewall.sh (mktemp + nft -c + nft -f).
#
# Входные переменные окружения (выставляет limits.sh после shield_limits_resolve):
#   SH_F_SSH_PORTS      "22 2222"
#   SH_F_PROTECTED_TCP  "443 8443"   (exclude.conf §30 уже вычтен)
#   SH_F_PROTECTED_UDP  "443"
#   SH_F_ADMIN_V4/V6    admin IP текущей сессии (whitelist, ТЗ §20)
#   SH_F_EXCL_V4/V6     CIDR из exclude.conf (§30)
#   SH_F_WAN_IFACE      дефолтный интерфейс (для анти-спуфа) или ""
#   SH_F_IPV6           1/0
#   SH_F_EXTENSIONS     glob-шаблон include расширений или ""
#   SH_F_ENABLE_ANTISPOOF 1/0 — drop private-src на WAN (opt-in)
#   SH_R_<NAME>         числа (rates/bursts/limits/timeouts/sizes)
#
# ВАЖНО (урок аудита): per-source rate-limit ТОЛЬКО через meter — plain
# `limit rate over` в правиле считает ГЛОБАЛЬНО. meter и log — в РАЗНЫХ правилах.
set -euo pipefail

shield_nft_emit_set() {
    # emit_set <name> <type> [опции-построчно...] ; элементы читаются из stdin (построчно)
    local name="$1" type="$2"; shift 2
    printf '    set %s {\n        type %s\n' "$name" "$type"
    local opt
    for opt in "$@"; do printf '        %s\n' "$opt"; done
    local elems=""
    elems="$(awk 'NF' | paste -sd, -)"
    [ -n "$elems" ] && printf '        elements = { %s }\n' "$elems"
    printf '    }\n'
}

shield_nft_build_ruleset() {
    local ts; ts="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    {
        cat <<EOF
#!/usr/sbin/nft -f
# ============================================================
# Generated by shieldnode v$SHIELD_VERSION at $ts — DO NOT EDIT.
# Таблица inet shieldnode (ТЗ §21): SSH-защита, invalid-drop,
# abuse-limiting TCP/UDP, temporary_blocklist. Policy accept.
# conntrack/sysctl ЗДЕСЬ НЕ ИЗМЕНЯЮТСЯ — единственный владелец node (ТЗ §15).
# Атомарность (ТЗ §26): mktemp + nft -c + nft -f.
# ============================================================
table inet shieldnode {
EOF

        # ---------- наборы (ТЗ §21–24) ----------
        echo "    # --- whitelist: админ-сессия (§20) + исключения (§30); interval для CIDR"
        { for ip in $SH_F_ADMIN_V4 $SH_F_EXCL_V4; do echo "$ip"; done; } \
            | shield_nft_emit_set whitelist_v4 ipv4_addr "flags interval" "auto-merge"
        if [ "$SH_F_IPV6" = "1" ]; then
            { for ip in $SH_F_ADMIN_V6 $SH_F_EXCL_V6; do echo "$ip"; done; } \
                | shield_nft_emit_set whitelist_v6 ipv6_addr "flags interval" "auto-merge"
        fi

        echo "    # --- abuse-наборы: timeout + max size (ТЗ §21–24)"
        printf '' | shield_nft_emit_set ssh_abusers ipv4_addr "size $SH_R_SSH_ABUSERS_SIZE" "timeout ${SH_R_SSH_ABUSERS_TIMEOUT}s"
        [ "$SH_F_IPV6" = "1" ] && printf '' | shield_nft_emit_set ssh_abusers_v6 ipv6_addr "size $SH_R_SSH_ABUSERS_SIZE" "timeout ${SH_R_SSH_ABUSERS_TIMEOUT}s"
        printf '' | shield_nft_emit_set tcp_abusers ipv4_addr "size $SH_R_TCP_ABUSERS_SIZE" "timeout ${SH_R_TCP_ABUSERS_TIMEOUT}s"
        [ "$SH_F_IPV6" = "1" ] && printf '' | shield_nft_emit_set tcp_abusers_v6 ipv6_addr "size $SH_R_TCP_ABUSERS_SIZE" "timeout ${SH_R_TCP_ABUSERS_TIMEOUT}s"
        printf '' | shield_nft_emit_set udp_abusers ipv4_addr "size $SH_R_UDP_ABUSERS_SIZE" "timeout ${SH_R_UDP_ABUSERS_TIMEOUT}s"
        [ "$SH_F_IPV6" = "1" ] && printf '' | shield_nft_emit_set udp_abusers_v6 ipv6_addr "size $SH_R_UDP_ABUSERS_SIZE" "timeout ${SH_R_UDP_ABUSERS_TIMEOUT}s"
        printf '' | shield_nft_emit_set temporary_blocklist ipv4_addr "size $SH_R_TEMP_BLOCKLIST_SIZE" "timeout ${SH_R_TEMP_BLOCKLIST_TIMEOUT}s"
        [ "$SH_F_IPV6" = "1" ] && printf '' | shield_nft_emit_set temporary_blocklist_v6 ipv6_addr "size $SH_R_TEMP_BLOCKLIST_SIZE" "timeout ${SH_R_TEMP_BLOCKLIST_TIMEOUT}s"

        echo "    # --- защищаемые порты (ssh + Xray-detected; exclude §30 вычтен)"
        for p in $SH_F_PROTECTED_TCP; do echo "$p"; done | shield_nft_emit_set protected_tcp inet_service "flags interval" "auto-merge"
        for p in $SH_F_PROTECTED_UDP; do echo "$p"; done | shield_nft_emit_set protected_udp inet_service "flags interval" "auto-merge"

        # --- blocklists: агрегаторы scanner/threat (+tor opt-in, custom) ---
        # Наборы наполняет updater (shieldnode-blocklist.timer). Имена совместимы
        # со старой веткой (scanner_blocklist_v4 и т.д.).
        if [ "${SH_F_ENABLE_BLOCKLISTS:-1}" = "1" ]; then
            if [ "${SH_F_ENABLE_SCANNER_LIST:-1}" = "1" ]; then
                printf '' | shield_nft_emit_set scanner_blocklist_v4 ipv4_addr "size $SH_R_SCANNER_BLOCKLIST_SIZE" "flags interval" "auto-merge"
                [ "$SH_F_IPV6" = "1" ] && printf '' | shield_nft_emit_set scanner_blocklist_v6 ipv6_addr "size $SH_R_SCANNER_BLOCKLIST_SIZE" "flags interval" "auto-merge"
            fi
            if [ "${SH_F_ENABLE_THREAT_LIST:-1}" = "1" ]; then
                printf '' | shield_nft_emit_set threat_blocklist_v4 ipv4_addr "size $SH_R_THREAT_BLOCKLIST_SIZE" "flags interval" "auto-merge"
                [ "$SH_F_IPV6" = "1" ] && printf '' | shield_nft_emit_set threat_blocklist_v6 ipv6_addr "size $SH_R_THREAT_BLOCKLIST_SIZE" "flags interval" "auto-merge"
            fi
            if [ "${SH_F_BLOCK_TOR:-0}" = "1" ]; then
                printf '' | shield_nft_emit_set tor_exit_blocklist_v4 ipv4_addr "size $SH_R_TOR_BLOCKLIST_SIZE" "flags interval" "auto-merge"
                [ "$SH_F_IPV6" = "1" ] && printf '' | shield_nft_emit_set tor_exit_blocklist_v6 ipv6_addr "size $SH_R_TOR_BLOCKLIST_SIZE" "flags interval" "auto-merge"
            fi
            if [ "${SH_F_ENABLE_CUSTOM_LIST:-1}" = "1" ]; then
                printf '' | shield_nft_emit_set custom_blocklist_v4 ipv4_addr "size $SH_R_CUSTOM_BLOCKLIST_SIZE" "flags interval" "auto-merge"
                [ "$SH_F_IPV6" = "1" ] && printf '' | shield_nft_emit_set custom_blocklist_v6 ipv6_addr "size $SH_R_CUSTOM_BLOCKLIST_SIZE" "flags interval" "auto-merge"
            fi
        fi

        # ---------- prerouting (ТЗ §21–25): priority -150, policy accept ----------
        cat <<EOF

    chain prerouting {
        type filter hook prerouting priority -150; policy accept;
EOF
        [ "$SH_F_ENABLE_ESTABLISHED" = "1" ] && cat <<'EOF'
        # established/related — вернувшийся трафик не трогаем (ТЗ §23)
        ct state established,related accept
EOF
        if [ "$SH_F_ENABLE_LOOPBACK" = "1" ]; then
            cat <<'EOF'
        # loopback: локальные проверки (sshd self-test, health-checks) — не баним сами себя
        iifname "lo" accept
EOF
        fi
        cat <<'EOF'
        # whitelist первым из блокирующих решений: админ/исключения §30 не режутся
        ip saddr @whitelist_v4 accept
EOF
        [ "$SH_F_IPV6" = "1" ] && echo "        ip6 saddr @whitelist_v6 accept"

        # --- агрегаторские блоклисты (scanner/threat/tor/custom): ПОСЛЕ whitelist,
        # чтобы админ и TRUSTED_IPS никогда не резались списками
        if [ "$SH_F_ENABLE_BLOCKLISTS" = "1" ]; then
            if [ "$SH_F_ENABLE_SCANNER_LIST" = "1" ]; then
                echo "        ip saddr @scanner_blocklist_v4 drop"
                [ "$SH_F_IPV6" = "1" ] && echo "        ip6 saddr @scanner_blocklist_v6 drop"
            fi
            if [ "$SH_F_ENABLE_THREAT_LIST" = "1" ]; then
                echo "        ip saddr @threat_blocklist_v4 drop"
                [ "$SH_F_IPV6" = "1" ] && echo "        ip6 saddr @threat_blocklist_v6 drop"
            fi
            if [ "$SH_F_BLOCK_TOR" = "1" ]; then
                echo "        ip saddr @tor_exit_blocklist_v4 drop"
                [ "$SH_F_IPV6" = "1" ] && echo "        ip6 saddr @tor_exit_blocklist_v6 drop"
            fi
            if [ "$SH_F_ENABLE_CUSTOM_LIST" = "1" ]; then
                echo "        ip saddr @custom_blocklist_v4 drop"
                [ "$SH_F_IPV6" = "1" ] && echo "        ip6 saddr @custom_blocklist_v6 drop"
            fi
        fi

        # --- анти-спуф (opt-in): приватные SRC на WAN-интерфейсе недопустимы
        if [ "$SH_F_ENABLE_ANTISPOOF" = "1" ] && [ -n "$SH_F_WAN_IFACE" ]; then
            cat <<EOF
        # анти-спуф: private/loopback/link-local/multicast SRC на $SH_F_WAN_IFACE -> drop
        iifname "$SH_F_WAN_IFACE" ip saddr { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 127.0.0.0/8, 169.254.0.0/16, 224.0.0.0/4 } drop
EOF
        fi

        if [ "$SH_F_ENABLE_INVALID_DROP" = "1" ]; then
            cat <<'EOF'
        # invalid-пакеты (ТЗ §22): битые CT + классические сканы флагами
        ct state invalid drop
        tcp flags & (fin|syn|rst|ack) == 0 drop
        tcp flags & (fin|syn) == fin|syn drop
        tcp flags & (syn|rst) == syn|rst drop
        tcp flags & (fin|rst) == fin|rst drop
        tcp flags & (fin|syn|rst|ack) == fin|syn|rst|ack drop
        tcp flags & (ack|fin) == fin drop
EOF
        fi

        cat <<'EOF'
        # temporary_blocklist (§24): ручные/аварийные блокировки с TTL
        ip saddr @temporary_blocklist drop
EOF
        [ "$SH_F_IPV6" = "1" ] && echo "        ip6 saddr @temporary_blocklist_v6 drop"

        cat <<'EOF'
        # повторные abusers — сразу drop (§21–23)
        ip saddr @ssh_abusers drop
EOF
        [ "$SH_F_IPV6" = "1" ] && echo "        ip6 saddr @ssh_abusers_v6 drop"

        # --- SSH-защита (ТЗ §19–20): только новые соединения; meter = per-source
        if [ "$SH_F_ENABLE_SSH_PROTECTION" = "1" ]; then
            local port
            for port in $SH_F_SSH_PORTS; do
                cat <<EOF
        # SSH port $port: новые > $SH_R_SSH_NEW_RATE/min burst $SH_R_SSH_NEW_BURST (per-src) -> ban
        tcp dport $port ct state new meter ssh_new_$port { ip saddr limit rate over $SH_R_SSH_NEW_RATE/minute burst $SH_R_SSH_NEW_BURST packets } add @ssh_abusers { ip saddr timeout ${SH_R_SSH_ABUSERS_TIMEOUT}s } drop
EOF
                [ "$SH_F_IPV6" = "1" ] && cat <<EOF
        tcp dport $port ct state new meter ssh_new6_$port { ip6 saddr limit rate over $SH_R_SSH_NEW_RATE/minute burst $SH_R_SSH_NEW_BURST packets } add @ssh_abusers_v6 { ip6 saddr timeout ${SH_R_SSH_ABUSERS_TIMEOUT}s } drop
EOF
                cat <<EOF
        # SSH port $port: > $SH_R_SSH_CONN_MAX conntrack с одного src -> ban (CGNAT: см. config.conf)
        tcp dport $port ip saddr ct count over $SH_R_SSH_CONN_MAX add @ssh_abusers { ip saddr timeout ${SH_R_SSH_ABUSERS_TIMEOUT}s } drop
EOF
                [ "$SH_F_IPV6" = "1" ] && cat <<EOF
        tcp dport $port ip6 saddr ct count over $SH_R_SSH_CONN_MAX add @ssh_abusers_v6 { ip6 saddr timeout ${SH_R_SSH_ABUSERS_TIMEOUT}s } drop
EOF
            done
        fi

        if [ "$SH_F_ENABLE_ABUSE_LIMITING" = "1" ]; then
            cat <<'EOF'
        ip saddr @tcp_abusers drop
EOF
            [ "$SH_F_IPV6" = "1" ] && echo "        ip6 saddr @tcp_abusers_v6 drop"

            # ENABLE_SYN_PROTECTION: мастер-выключатель именно SYN-rate правила
            # (new-rate и conn-limit независимы и остаются при SYN_PROTECTION=0)
            if [ "${SH_F_ENABLE_SYN_PROTECTION:-1}" = "1" ]; then
                cat <<EOF
        # TCP-политика (§23): SYN-флуд per-src > $SH_R_TCP_SYN_RATE/s burst $SH_R_TCP_SYN_BURST
        tcp dport @protected_tcp tcp flags syn ct state new meter tcp_syn { ip saddr limit rate over $SH_R_TCP_SYN_RATE/second burst $SH_R_TCP_SYN_BURST packets } add @tcp_abusers { ip saddr timeout ${SH_R_TCP_ABUSERS_TIMEOUT}s } drop
EOF
                [ "$SH_F_IPV6" = "1" ] && cat <<EOF
        tcp dport @protected_tcp tcp flags syn ct state new meter tcp_syn6 { ip6 saddr limit rate over $SH_R_TCP_SYN_RATE/second burst $SH_R_TCP_SYN_BURST packets } add @tcp_abusers_v6 { ip6 saddr timeout ${SH_R_TCP_ABUSERS_TIMEOUT}s } drop
EOF
            fi
            cat <<EOF
        # TCP-политика: новые соединения per-src > $SH_R_TCP_NEW_RATE/min burst $SH_R_TCP_NEW_BURST
        tcp dport @protected_tcp ct state new meter tcp_new { ip saddr limit rate over $SH_R_TCP_NEW_RATE/minute burst $SH_R_TCP_NEW_BURST packets } add @tcp_abusers { ip saddr timeout ${SH_R_TCP_ABUSERS_TIMEOUT}s } drop
EOF
            [ "$SH_F_IPV6" = "1" ] && cat <<EOF
        tcp dport @protected_tcp ct state new meter tcp_new6 { ip6 saddr limit rate over $SH_R_TCP_NEW_RATE/minute burst $SH_R_TCP_NEW_BURST packets } add @tcp_abusers_v6 { ip6 saddr timeout ${SH_R_TCP_ABUSERS_TIMEOUT}s } drop
EOF
            cat <<EOF
        # TCP-политика: > $SH_R_TCP_CONN_MAX conntrack с одного src (CGNAT-лояльно)
        tcp dport @protected_tcp ct state new ip saddr ct count over $SH_R_TCP_CONN_MAX add @tcp_abusers { ip saddr timeout ${SH_R_TCP_ABUSERS_TIMEOUT}s } drop
EOF
            [ "$SH_F_IPV6" = "1" ] && cat <<EOF
        tcp dport @protected_tcp ct state new ip6 saddr ct count over $SH_R_TCP_CONN_MAX add @tcp_abusers_v6 { ip6 saddr timeout ${SH_R_TCP_ABUSERS_TIMEOUT}s } drop
EOF
            if [ "$SH_R_TCP_GLOBAL_CEIL" -gt 0 ]; then
                cat <<EOF
        # TCP global ceiling (§23): > $SH_R_TCP_GLOBAL_CEIL SYN/мин на ВСЮ ноду -> drop (бан не вешаем)
        tcp flags syn ct state new limit rate over $SH_R_TCP_GLOBAL_CEIL/minute drop
EOF
            fi
            cat <<'EOF'
        ip saddr @udp_abusers drop
EOF
            [ "$SH_F_IPV6" = "1" ] && echo "        ip6 saddr @udp_abusers_v6 drop"
            cat <<EOF
        # UDP-политика (§23): per-src > $SH_R_UDP_RATE/s burst $SH_R_UDP_BURST
        udp dport @protected_udp meter udp_rate { ip saddr limit rate over $SH_R_UDP_RATE/second burst $SH_R_UDP_BURST packets } add @udp_abusers { ip saddr timeout ${SH_R_UDP_ABUSERS_TIMEOUT}s } drop
EOF
            [ "$SH_F_IPV6" = "1" ] && cat <<EOF
        udp dport @protected_udp meter udp_rate6 { ip6 saddr limit rate over $SH_R_UDP_RATE/second burst $SH_R_UDP_BURST packets } add @udp_abusers_v6 { ip6 saddr timeout ${SH_R_UDP_ABUSERS_TIMEOUT}s } drop
EOF
            if [ "$SH_R_UDP_GLOBAL_CEIL" -gt 0 ]; then
                cat <<EOF
        # UDP global ceiling: > $SH_R_UDP_GLOBAL_CEIL пакетов/с на всю ноду -> drop
        udp dport @protected_udp limit rate over $SH_R_UDP_GLOBAL_CEIL/second drop
EOF
            fi
        fi

        # --- расширения: include внутри таблицы (Stage-2, «расширения»).
        #    Баунсер ДО whitelist: собственный base-chain priority -200; ПОСЛЕ: -140.
        if [ -n "$SH_F_EXTENSIONS" ]; then
            echo "        include \"$SH_F_EXTENSIONS\""
        fi

        cat <<'EOF'
    }
EOF

        # ---------- input: loopback (ТЗ §23) ----------
        if [ "$SH_F_ENABLE_LOOPBACK" = "1" ]; then
            cat <<'EOF'

    chain input {
        type filter hook input priority -150; policy accept;
        # loopback-трафик (локальные сервисы, health-checks) — не трогаем
        iifname "lo" accept
    }
EOF
        fi

        echo "}"
    }
}
