#!/bin/bash
# shieldnode — lib/nft.sh: генератор таблицы inet shieldnode (ТЗ §21–26, §30).
# Только ГЕНЕРАЦИЯ текста ruleset. Применение — в firewall.sh (mktemp + nft -c + nft -f).
#
# Входные переменные окружения (выставляет limits.sh после shield_limits_resolve):
#   SH_F_SSH_PORTS      "22 2222"
#   SH_F_PROTECTED_TCP  "443 8443"   (exclude.conf §30 уже вычтен)
#   SH_F_PROTECTED_UDP  "443"
#   SH_F_ADMIN_V4/V6    admin IP текущей сессии (whitelist, ТЗ §20)
#   SH_F_EXCL_V4/V6     CIDR из exclude.conf (§30)
#   SH_F_WAN_IFACE      дефолтный интерфейс (для анти-спуфа) или ""
#   SH_F_IPV6           1/0
#   SH_F_EXTENSIONS     glob-шаблон include расширений или ""
#   SH_F_ENABLE_ANTISPOOF 1/0 — drop private-src на WAN (opt-in)
#   SH_R_<NAME>         числа (rates/bursts/limits/timeouts/sizes)
#
# ВАЖНО (урок аудита): per-source rate-limit ТОЛЬКО через meter — plain
# `limit rate over` в правиле считает ГЛОБАЛЬНО. meter и log — в РАЗНЫХ правилах.
set -euo pipefail

shield_nft_emit_set() {
    # emit_set <name> <type> [опции-построчно...] ; элементы читаются из stdin (построчно)
    local name="$1" type="$2"; shift 2
    printf '    set %s {\n        type %s\n' "$name" "$type"
    local opt
    for opt in "$@"; do printf '        %s\n' "$opt"; done
    local elems=""
    elems="$(awk 'NF' | paste -sd, -)"
    [ -n "$elems" ] && printf '        elements = { %s }\n' "$elems"
    printf '    }\n'
}

# 2026-09-24 (v1.1.4): interval-сет `size S` вмещает меньше S/2 несмежных интервалов
# (в ядре каждый — узел начала + узел конца, плюс один служебный). Замер nft 1.0.9 /
# ядро 6.8, flush+add одной транзакцией (как updater): N записей требуют S >= 2N+1
# (N=1/10/1000/5000: 2N — ENFILE, 2N+1 — ок, в т.ч. refill полного сета). Блоклисты
# объявляются с size 2*<X>_BLOCKLIST_SIZE+1, чтобы значение конфига означало ЗАПИСИ.
# size — предел, память не преаллоцируется.
shield_nft_build_ruleset() {
    local ts; ts="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    {
        cat <<EOF
table inet shieldnode
delete table inet shieldnode
# ============================================================
# Generated by shieldnode v$SHIELD_VERSION at $ts — DO NOT EDIT.
# Таблица inet shieldnode (ТЗ §21): SSH-защита, invalid-drop,
# abuse-limiting TCP/UDP, temporary_blocklist. Policy accept.
# conntrack/sysctl ЗДЕСЬ НЕ ИЗМЕНЯЮТСЯ — единственный владелец node (ТЗ §15).
# Атомарность (ТЗ §26): mktemp + nft -c + nft -f; тройка table/delete/table
# выше (эталон старого прод-стека) делает замену атомарной одной транзакцией:
# meter — именованный dynset, без delete повторный apply падает на EBUSY,
# а внешний destroy до nft -f открывал fail-open окно (баг 2026-09-22, nft 1.0.6).
# ============================================================
table inet shieldnode {
EOF

        # ---------- наборы (ТЗ §21–24) ----------
        echo "    # --- whitelist: админ-сессия (§20) + исключения (§30); interval для CIDR"
        { for ip in $SH_F_ADMIN_V4 $SH_F_EXCL_V4; do echo "$ip"; done; } \
            | shield_nft_emit_set whitelist_v4 ipv4_addr "flags interval" "auto-merge"
        if [ "$SH_F_IPV6" = "1" ]; then
            { for ip in $SH_F_ADMIN_V6 $SH_F_EXCL_V6; do echo "$ip"; done; } \
                | shield_nft_emit_set whitelist_v6 ipv6_addr "flags interval" "auto-merge"
        fi

        echo "    # --- abuse-наборы: timeout + max size (ТЗ §21–24)"
        # flags dynamic ОБЯЗАТЕЛЕН: наборы наполняются ИЗ ПРАВИЛ (add @...).
        # Без него nft -c падает — реальный баг 2026-09-22 (nft 1.8.10/Ubuntu 24.04)
        printf '' | shield_nft_emit_set ssh_abusers ipv4_addr "size $SH_R_SSH_ABUSERS_SIZE" "flags dynamic" "timeout ${SH_R_SSH_ABUSERS_TIMEOUT}s"
        [ "$SH_F_IPV6" = "1" ] && printf '' | shield_nft_emit_set ssh_abusers_v6 ipv6_addr "size $SH_R_SSH_ABUSERS_SIZE" "flags dynamic" "timeout ${SH_R_SSH_ABUSERS_TIMEOUT}s"
        printf '' | shield_nft_emit_set tcp_abusers ipv4_addr "size $SH_R_TCP_ABUSERS_SIZE" "flags dynamic" "timeout ${SH_R_TCP_ABUSERS_TIMEOUT}s"
        [ "$SH_F_IPV6" = "1" ] && printf '' | shield_nft_emit_set tcp_abusers_v6 ipv6_addr "size $SH_R_TCP_ABUSERS_SIZE" "flags dynamic" "timeout ${SH_R_TCP_ABUSERS_TIMEOUT}s"
        printf '' | shield_nft_emit_set udp_abusers ipv4_addr "size $SH_R_UDP_ABUSERS_SIZE" "flags dynamic" "timeout ${SH_R_UDP_ABUSERS_TIMEOUT}s"
        [ "$SH_F_IPV6" = "1" ] && printf '' | shield_nft_emit_set udp_abusers_v6 ipv6_addr "size $SH_R_UDP_ABUSERS_SIZE" "flags dynamic" "timeout ${SH_R_UDP_ABUSERS_TIMEOUT}s"
        printf '' | shield_nft_emit_set temporary_blocklist ipv4_addr "size $SH_R_TEMP_BLOCKLIST_SIZE" "flags dynamic" "timeout ${SH_R_TEMP_BLOCKLIST_TIMEOUT}s"
        [ "$SH_F_IPV6" = "1" ] && printf '' | shield_nft_emit_set temporary_blocklist_v6 ipv6_addr "size $SH_R_TEMP_BLOCKLIST_SIZE" "flags dynamic" "timeout ${SH_R_TEMP_BLOCKLIST_TIMEOUT}s"

        # --- connlimit-наборы: concurrent connections per source (ТЗ §23).
        # ct count — ТОЛЬКО внутри add @set { ip saddr ct count over N } и набор
        # ОБЯЗАН быть БЕЗ timeout (иначе "Operation not supported" — wiki nftables;
        # баг 2026-09-22: standalone `ip saddr ct count over N` — syntax error).
        # Элементы чистятся conntrack-таймерами ядра при закрытии соединений.
        printf '' | shield_nft_emit_set ssh_connlimit ipv4_addr "size $SH_R_SSH_ABUSERS_SIZE" "flags dynamic"
        [ "$SH_F_IPV6" = "1" ] && printf '' | shield_nft_emit_set ssh_connlimit_v6 ipv6_addr "size $SH_R_SSH_ABUSERS_SIZE" "flags dynamic"
        printf '' | shield_nft_emit_set tcp_connlimit ipv4_addr "size $SH_R_TCP_ABUSERS_SIZE" "flags dynamic"
        [ "$SH_F_IPV6" = "1" ] && printf '' | shield_nft_emit_set tcp_connlimit_v6 ipv6_addr "size $SH_R_TCP_ABUSERS_SIZE" "flags dynamic"

        echo "    # --- защищаемые порты (ssh + Xray-detected; exclude §30 вычтен)"
        for p in $SH_F_PROTECTED_TCP; do echo "$p"; done | shield_nft_emit_set protected_tcp inet_service "flags interval" "auto-merge"
        for p in $SH_F_PROTECTED_UDP; do echo "$p"; done | shield_nft_emit_set protected_udp inet_service "flags interval" "auto-merge"

        # --- blocklists: агрегаторы scanner/threat (+tor opt-in, custom) ---
        # Наборы наполняет updater (shieldnode-blocklist.timer). Имена совместимы
        # со старой веткой (scanner_blocklist_v4 и т.д.).
        if [ "${SH_F_ENABLE_BLOCKLISTS:-1}" = "1" ]; then
            if [ "${SH_F_ENABLE_SCANNER_LIST:-1}" = "1" ]; then
                printf '' | shield_nft_emit_set scanner_blocklist_v4 ipv4_addr "size $((2 * SH_R_SCANNER_BLOCKLIST_SIZE + 1))" "flags interval" "auto-merge"
                [ "$SH_F_IPV6" = "1" ] && printf '' | shield_nft_emit_set scanner_blocklist_v6 ipv6_addr "size $((2 * SH_R_SCANNER_BLOCKLIST_SIZE + 1))" "flags interval" "auto-merge"
            fi
            if [ "${SH_F_ENABLE_THREAT_LIST:-1}" = "1" ]; then
                printf '' | shield_nft_emit_set threat_blocklist_v4 ipv4_addr "size $((2 * SH_R_THREAT_BLOCKLIST_SIZE + 1))" "flags interval" "auto-merge"
                [ "$SH_F_IPV6" = "1" ] && printf '' | shield_nft_emit_set threat_blocklist_v6 ipv6_addr "size $((2 * SH_R_THREAT_BLOCKLIST_SIZE + 1))" "flags interval" "auto-merge"
            fi
            if [ "${SH_F_BLOCK_TOR:-0}" = "1" ]; then
                printf '' | shield_nft_emit_set tor_exit_blocklist_v4 ipv4_addr "size $((2 * SH_R_TOR_BLOCKLIST_SIZE + 1))" "flags interval" "auto-merge"
                [ "$SH_F_IPV6" = "1" ] && printf '' | shield_nft_emit_set tor_exit_blocklist_v6 ipv6_addr "size $((2 * SH_R_TOR_BLOCKLIST_SIZE + 1))" "flags interval" "auto-merge"
            fi
            if [ "${SH_F_ENABLE_CUSTOM_LIST:-1}" = "1" ]; then
                printf '' | shield_nft_emit_set custom_blocklist_v4 ipv4_addr "size $((2 * SH_R_CUSTOM_BLOCKLIST_SIZE + 1))" "flags interval" "auto-merge"
                [ "$SH_F_IPV6" = "1" ] && printf '' | shield_nft_emit_set custom_blocklist_v6 ipv6_addr "size $((2 * SH_R_CUSTOM_BLOCKLIST_SIZE + 1))" "flags interval" "auto-merge"
            fi
            # crowdsec community blocklist (Blocklist-as-a-Service, plain-text feed):
            # качается updater'ом с Basic-Auth endpoint'а консоли, 1 раз/24ч (лимит тарифа)
            if [ "${SH_F_ENABLE_CROWDSEC_LIST:-0}" = "1" ]; then
                printf '' | shield_nft_emit_set crowdsec_blocklist_v4 ipv4_addr "size $((2 * SH_R_CROWDSEC_BLOCKLIST_SIZE + 1))" "flags interval" "auto-merge"
                [ "$SH_F_IPV6" = "1" ] && printf '' | shield_nft_emit_set crowdsec_blocklist_v6 ipv6_addr "size $((2 * SH_R_CROWDSEC_BLOCKLIST_SIZE + 1))" "flags interval" "auto-merge"
            fi
            # spamhaus DROP/EDROP (+v6) — worst-of-the-worst hijacked space, бесплатно,
            # без ключа. Формат "S24-x.y.z.w/24 ; comment" — парсится updater'ом.
            if [ "${SH_F_ENABLE_SPAMHAUS_LIST:-1}" = "1" ]; then
                printf '' | shield_nft_emit_set spamhaus_blocklist_v4 ipv4_addr "size $((2 * SH_R_SPAMHAUS_BLOCKLIST_SIZE + 1))" "flags interval" "auto-merge"
                [ "$SH_F_IPV6" = "1" ] && printf '' | shield_nft_emit_set spamhaus_blocklist_v6 ipv6_addr "size $((2 * SH_R_SPAMHAUS_BLOCKLIST_SIZE + 1))" "flags interval" "auto-merge"
            fi
            # CINS Army (Collective Intelligence Network Security, ~30k IP) — бесплатно, без ключа
            if [ "${SH_F_ENABLE_CINS_LIST:-1}" = "1" ]; then
                printf '' | shield_nft_emit_set cins_blocklist_v4 ipv4_addr "size $((2 * SH_R_CINS_BLOCKLIST_SIZE + 1))" "flags interval" "auto-merge"
            fi
        fi

        # --- named counters: наблюдаемость дропов БЕЗ log (ТЗ запрещает log-флуд).
        # Счётчик = метаданные ядра, в userspace ничего не копируется, стоимость ~0.
        echo "    # --- drop-counters (zero-cost observability)"
        local __c
        for __c in scanner_v4 scanner_v6 threat_v4 threat_v6 tor_v4 tor_v6 custom_v4 custom_v6 antispoof antispoof_v6 invalid temp_v4 temp_v6 ssh_abusers_v4 ssh_abusers_v6 tcp_abusers_v4 tcp_abusers_v6 udp_abusers_v4 udp_abusers_v6 syn_v4 syn_v6 global_tcp global_udp; do
            echo "    counter c_drops_$__c { }"
        done
        # crowdsec/spamhaus/cins-counters — только при включённом фиде (правила тоже условные)
        if [ "${SH_F_ENABLE_CROWDSEC_LIST:-0}" = "1" ]; then
            echo "    counter c_drops_crowdsec_v4 { }"
            [ "$SH_F_IPV6" = "1" ] && echo "    counter c_drops_crowdsec_v6 { }"
        fi
        if [ "${SH_F_ENABLE_SPAMHAUS_LIST:-1}" = "1" ]; then
            echo "    counter c_drops_spamhaus_v4 { }"
            [ "$SH_F_IPV6" = "1" ] && echo "    counter c_drops_spamhaus_v6 { }"
        fi
        if [ "${SH_F_ENABLE_CINS_LIST:-1}" = "1" ]; then
            echo "    counter c_drops_cins_v4 { }"
        fi
        # amp/icmp-counters — при включённых соответствующих гардах
        [ "${SH_F_ENABLE_AMP_GUARD:-1}" = "1" ] && echo "    counter c_drops_amp { }"
        [ "${SH_F_ENABLE_ICMP_GUARD:-1}" = "1" ] && echo "    counter c_drops_icmp { }"

        # ---------- prerouting (ТЗ §21–25): priority -150, policy accept ----------
        cat <<EOF

    chain prerouting {
        type filter hook prerouting priority -150; policy accept;
EOF
        [ "$SH_F_ENABLE_ESTABLISHED" = "1" ] && cat <<'EOF'
        # established/related — вернувшийся трафик не трогаем (ТЗ §23)
        ct state established,related accept
EOF
        if [ "$SH_F_ENABLE_LOOPBACK" = "1" ]; then
            cat <<'EOF'
        # loopback: локальные проверки (sshd self-test, health-checks) — не баним сами себя
        iifname "lo" accept
EOF
        fi
        cat <<'EOF'
        # whitelist первым из блокирующих решений: админ/исключения §30 не режутся
        ip saddr @whitelist_v4 accept
EOF
        [ "$SH_F_IPV6" = "1" ] && echo "        ip6 saddr @whitelist_v6 accept"

        # --- агрегаторские блоклисты (scanner/threat/tor/custom): ПОСЛЕ whitelist,
        # чтобы админ и TRUSTED_IPS никогда не резались списками
        if [ "$SH_F_ENABLE_BLOCKLISTS" = "1" ]; then
            if [ "$SH_F_ENABLE_SCANNER_LIST" = "1" ]; then
                echo "        ip saddr @scanner_blocklist_v4 counter name c_drops_scanner_v4 drop"
                [ "$SH_F_IPV6" = "1" ] && echo "        ip6 saddr @scanner_blocklist_v6 counter name c_drops_scanner_v6 drop"
            fi
            if [ "$SH_F_ENABLE_THREAT_LIST" = "1" ]; then
                echo "        ip saddr @threat_blocklist_v4 counter name c_drops_threat_v4 drop"
                [ "$SH_F_IPV6" = "1" ] && echo "        ip6 saddr @threat_blocklist_v6 counter name c_drops_threat_v6 drop"
            fi
            if [ "$SH_F_BLOCK_TOR" = "1" ]; then
                echo "        ip saddr @tor_exit_blocklist_v4 counter name c_drops_tor_v4 drop"
                [ "$SH_F_IPV6" = "1" ] && echo "        ip6 saddr @tor_exit_blocklist_v6 counter name c_drops_tor_v6 drop"
            fi
            if [ "$SH_F_ENABLE_CUSTOM_LIST" = "1" ]; then
                echo "        ip saddr @custom_blocklist_v4 counter name c_drops_custom_v4 drop"
                [ "$SH_F_IPV6" = "1" ] && echo "        ip6 saddr @custom_blocklist_v6 counter name c_drops_custom_v6 drop"
            fi
            if [ "${SH_F_ENABLE_CROWDSEC_LIST:-0}" = "1" ]; then
                echo "        ip saddr @crowdsec_blocklist_v4 counter name c_drops_crowdsec_v4 drop"
                [ "$SH_F_IPV6" = "1" ] && echo "        ip6 saddr @crowdsec_blocklist_v6 counter name c_drops_crowdsec_v6 drop"
            fi
            if [ "${SH_F_ENABLE_SPAMHAUS_LIST:-1}" = "1" ]; then
                echo "        ip saddr @spamhaus_blocklist_v4 counter name c_drops_spamhaus_v4 drop"
                [ "$SH_F_IPV6" = "1" ] && echo "        ip6 saddr @spamhaus_blocklist_v6 counter name c_drops_spamhaus_v6 drop"
            fi
            if [ "${SH_F_ENABLE_CINS_LIST:-1}" = "1" ]; then
                echo "        ip saddr @cins_blocklist_v4 counter name c_drops_cins_v4 drop"
            fi
        fi

        # --- amplification-guard (anti-reflection, opt-out): входящие NEW UDP с
        # известных amplifier source-портов (DNS/NTP/SSDP/memcached/CLDAP) — это
        # неспрошенные ответы. Свои запросы (DNS и т.п.) идут как ESTABLISHED
        # (conntrack у нас же) — правило их не трогает.
        if [ "${SH_F_ENABLE_AMP_GUARD:-1}" = "1" ]; then
            cat <<'EOF'
        # anti-amplification: NEW udp с source-портов 53/123/1900/11211/389 -> drop
        meta l4proto udp ct state new udp sport { 53, 123, 1900, 11211, 389 } counter name c_drops_amp drop
EOF
        fi

        # --- ICMP-политика (opt-out): PMTUD для v6 НЕ ломаем (packet-too-big/
        # time-exceeded/parameter-problem всегда accept), echo-request душим.
        if [ "${SH_F_ENABLE_ICMP_GUARD:-1}" = "1" ]; then
            cat <<'EOF'
        # ICMPv6 essentials: без packet-too-big IPv6-туннели деградируют молча (PMTUD)
        icmpv6 type { packet-too-big, time-exceeded, parameter-problem } accept
        # echo-request: rate-limit per-src (здоровый ping жив, флод душим)
        # 2026-09-24 (v1.1.4): meter по saddr — раньше `limit` был ГЛОБАЛЬНЫМ (backlog #4):
        # флуд одного источника резал легитимный ping остальных. Лимит видит только
        # НОВЫЕ ICMP-потоки: echo в рамках одного id — ct established и принимается выше
        # (accept established до любого drop — жёсткое ограничение anti-lockout).
        ip protocol icmp icmp type echo-request meter icmp_echo4 { ip saddr limit rate over 10/second burst 20 packets } counter name c_drops_icmp drop
        icmpv6 type echo-request meter icmp_echo6 { ip6 saddr limit rate over 10/second burst 20 packets } counter name c_drops_icmp drop
EOF
        fi

        # --- анти-спуф (opt-in): приватные SRC на WAN-интерфейсе недопустимы
        if [ "$SH_F_ENABLE_ANTISPOOF" = "1" ] && [ -n "$SH_F_WAN_IFACE" ]; then
            cat <<EOF
        # анти-спуф: private/loopback/link-local/multicast SRC на $SH_F_WAN_IFACE -> drop
        iifname "$SH_F_WAN_IFACE" ip saddr { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 127.0.0.0/8, 169.254.0.0/16, 224.0.0.0/4 } counter name c_drops_antispoof drop
EOF
            # v6-аналог: loopback/ULA/link-local/multicast/documentation SRC на WAN
            [ "$SH_F_IPV6" = "1" ] && cat <<EOF
        # анти-спуф v6: loopback/ULA/link-local/multicast/doc SRC на $SH_F_WAN_IFACE -> drop
        iifname "$SH_F_WAN_IFACE" ip6 saddr { ::1, fc00::/7, fe80::/10, ff00::/8, 2001:db8::/32 } counter name c_drops_antispoof_v6 drop
EOF
        fi

        if [ "$SH_F_ENABLE_INVALID_DROP" = "1" ]; then
            cat <<'EOF'
        # invalid-пакеты (ТЗ §22): битые CT + классические сканы флагами
        ct state invalid counter name c_drops_invalid drop
        tcp flags & (fin|syn|rst|ack) == 0 counter name c_drops_invalid drop
        tcp flags & (fin|syn) == fin|syn counter name c_drops_invalid drop
        tcp flags & (syn|rst) == syn|rst counter name c_drops_invalid drop
        tcp flags & (fin|rst) == fin|rst counter name c_drops_invalid drop
        tcp flags & (fin|syn|rst|ack) == fin|syn|rst|ack counter name c_drops_invalid drop
        tcp flags & (ack|fin) == fin counter name c_drops_invalid drop
EOF
        fi

        cat <<'EOF'
        # temporary_blocklist (§24): ручные/аварийные блокировки с TTL
        ip saddr @temporary_blocklist counter name c_drops_temp_v4 drop
EOF
        [ "$SH_F_IPV6" = "1" ] && echo "        ip6 saddr @temporary_blocklist_v6 counter name c_drops_temp_v6 drop"

        cat <<'EOF'
        # повторные abusers — сразу drop (§21–23)
        ip saddr @ssh_abusers counter name c_drops_ssh_abusers_v4 drop
EOF
        [ "$SH_F_IPV6" = "1" ] && echo "        ip6 saddr @ssh_abusers_v6 counter name c_drops_ssh_abusers_v6 drop"

        # --- SSH-защита (ТЗ §19–20): только новые соединения; meter = per-source
        if [ "$SH_F_ENABLE_SSH_PROTECTION" = "1" ]; then
            local port
            for port in $SH_F_SSH_PORTS; do
                cat <<EOF
        # SSH port $port: новые > $SH_R_SSH_NEW_RATE/min burst $SH_R_SSH_NEW_BURST (per-src) -> ban
        tcp dport $port ct state new meter ssh_new_$port { ip saddr limit rate over $SH_R_SSH_NEW_RATE/minute burst $SH_R_SSH_NEW_BURST packets } add @ssh_abusers { ip saddr timeout ${SH_R_SSH_ABUSERS_TIMEOUT}s } counter name c_drops_ssh_abusers_v4 drop
EOF
                [ "$SH_F_IPV6" = "1" ] && cat <<EOF
        tcp dport $port ct state new meter ssh_new6_$port { ip6 saddr limit rate over $SH_R_SSH_NEW_RATE/minute burst $SH_R_SSH_NEW_BURST packets } add @ssh_abusers_v6 { ip6 saddr timeout ${SH_R_SSH_ABUSERS_TIMEOUT}s } counter name c_drops_ssh_abusers_v6 drop
EOF
                cat <<EOF
        # SSH port $port: > $SH_R_SSH_CONN_MAX одновременных conntrack с одного src -> drop
        # (ct count — только внутри add @set; набор без timeout, чистят conntrack-таймеры)
        tcp dport $port ct state new add @ssh_connlimit { ip saddr ct count over $SH_R_SSH_CONN_MAX } counter name c_drops_ssh_abusers_v4 drop
EOF
                [ "$SH_F_IPV6" = "1" ] && cat <<EOF
        tcp dport $port ct state new add @ssh_connlimit_v6 { ip6 saddr ct count over $SH_R_SSH_CONN_MAX } counter name c_drops_ssh_abusers_v6 drop
EOF
            done
        fi

        if [ "$SH_F_ENABLE_ABUSE_LIMITING" = "1" ]; then
            cat <<'EOF'
        ip saddr @tcp_abusers counter name c_drops_tcp_abusers_v4 drop
EOF
            [ "$SH_F_IPV6" = "1" ] && echo "        ip6 saddr @tcp_abusers_v6 counter name c_drops_tcp_abusers_v6 drop"

            # ENABLE_SYN_PROTECTION: мастер-выключатель именно SYN-rate правила
            # (new-rate и conn-limit независимы и остаются при SYN_PROTECTION=0)
            if [ "${SH_F_ENABLE_SYN_PROTECTION:-1}" = "1" ]; then
                cat <<EOF
        # TCP-политика (§23): SYN-флуд per-src > $SH_R_TCP_SYN_RATE/s burst $SH_R_TCP_SYN_BURST
        tcp dport @protected_tcp tcp flags syn ct state new meter tcp_syn { ip saddr limit rate over $SH_R_TCP_SYN_RATE/second burst $SH_R_TCP_SYN_BURST packets } add @tcp_abusers { ip saddr timeout ${SH_R_TCP_ABUSERS_TIMEOUT}s } counter name c_drops_syn_v4 drop
EOF
                [ "$SH_F_IPV6" = "1" ] && cat <<EOF
        tcp dport @protected_tcp tcp flags syn ct state new meter tcp_syn6 { ip6 saddr limit rate over $SH_R_TCP_SYN_RATE/second burst $SH_R_TCP_SYN_BURST packets } add @tcp_abusers_v6 { ip6 saddr timeout ${SH_R_TCP_ABUSERS_TIMEOUT}s } counter name c_drops_syn_v6 drop
EOF
            fi
            cat <<EOF
        # TCP-политика: новые соединения per-src > $SH_R_TCP_NEW_RATE/min burst $SH_R_TCP_NEW_BURST
        tcp dport @protected_tcp ct state new meter tcp_new { ip saddr limit rate over $SH_R_TCP_NEW_RATE/minute burst $SH_R_TCP_NEW_BURST packets } add @tcp_abusers { ip saddr timeout ${SH_R_TCP_ABUSERS_TIMEOUT}s } counter name c_drops_tcp_abusers_v4 drop
EOF
            [ "$SH_F_IPV6" = "1" ] && cat <<EOF
        tcp dport @protected_tcp ct state new meter tcp_new6 { ip6 saddr limit rate over $SH_R_TCP_NEW_RATE/minute burst $SH_R_TCP_NEW_BURST packets } add @tcp_abusers_v6 { ip6 saddr timeout ${SH_R_TCP_ABUSERS_TIMEOUT}s } counter name c_drops_tcp_abusers_v6 drop
EOF
            cat <<EOF
        # TCP-политика: > $SH_R_TCP_CONN_MAX одновременных conntrack с одного src (CGNAT-лояльно)
        tcp dport @protected_tcp ct state new add @tcp_connlimit { ip saddr ct count over $SH_R_TCP_CONN_MAX } counter name c_drops_tcp_abusers_v4 drop
EOF
            [ "$SH_F_IPV6" = "1" ] && cat <<EOF
        tcp dport @protected_tcp ct state new add @tcp_connlimit_v6 { ip6 saddr ct count over $SH_R_TCP_CONN_MAX } counter name c_drops_tcp_abusers_v6 drop
EOF
            if [ "$SH_R_TCP_GLOBAL_CEIL" -gt 0 ]; then
                cat <<EOF
        # TCP global ceiling (§23): > $SH_R_TCP_GLOBAL_CEIL SYN/мин на защищённые порты -> drop (бан не вешаем)
        # scope @protected_tcp ОБЯЗАТЕЛЕН: без него потолок бьёт и по SSH (локаут)
        tcp dport @protected_tcp tcp flags syn ct state new limit rate over $SH_R_TCP_GLOBAL_CEIL/minute counter name c_drops_global_tcp drop
EOF
            fi
            cat <<'EOF'
        ip saddr @udp_abusers counter name c_drops_udp_abusers_v4 drop
EOF
            [ "$SH_F_IPV6" = "1" ] && echo "        ip6 saddr @udp_abusers_v6 counter name c_drops_udp_abusers_v6 drop"
            cat <<EOF
        # UDP-политика (§23): per-src > $SH_R_UDP_RATE/s burst $SH_R_UDP_BURST
        udp dport @protected_udp meter udp_rate { ip saddr limit rate over $SH_R_UDP_RATE/second burst $SH_R_UDP_BURST packets } add @udp_abusers { ip saddr timeout ${SH_R_UDP_ABUSERS_TIMEOUT}s } counter name c_drops_udp_abusers_v4 drop
EOF
            [ "$SH_F_IPV6" = "1" ] && cat <<EOF
        udp dport @protected_udp meter udp_rate6 { ip6 saddr limit rate over $SH_R_UDP_RATE/second burst $SH_R_UDP_BURST packets } add @udp_abusers_v6 { ip6 saddr timeout ${SH_R_UDP_ABUSERS_TIMEOUT}s } counter name c_drops_udp_abusers_v6 drop
EOF
            if [ "$SH_R_UDP_GLOBAL_CEIL" -gt 0 ]; then
                cat <<EOF
        # UDP global ceiling: > $SH_R_UDP_GLOBAL_CEIL пакетов/с на всю ноду -> drop
        udp dport @protected_udp limit rate over $SH_R_UDP_GLOBAL_CEIL/second counter name c_drops_global_udp drop
EOF
            fi
        fi

        # --- расширения: include внутри таблицы (Stage-2, «расширения»).
        #    Баунсер ДО whitelist: собственный base-chain priority -200; ПОСЛЕ: -140.
        if [ -n "$SH_F_EXTENSIONS" ]; then
            echo "        include \"$SH_F_EXTENSIONS\""
        fi

        cat <<'EOF'
    }
EOF

        # ---------- input: loopback (ТЗ §23) ----------
        if [ "$SH_F_ENABLE_LOOPBACK" = "1" ]; then
            cat <<'EOF'

    chain input {
        type filter hook input priority -150; policy accept;
        # loopback-трафик (локальные сервисы, health-checks) — не трогаем
        iifname "lo" accept
    }
EOF
        fi

        echo "}"
    }
}
